### PR TITLE
fix(ui): lab page collapsible draft oder

### LINKED ISSUE #147: Order drafts in the lab page in reverse-chronological order
Currently, when a faculty member views the students accepted by the lab in the past draft, the drafts are ordered chronologically (i.e., older drafts appear higher). Ideally, it should be in reverse-chronological order, so newer drafts should be closer to the top (e.g., Draft 3 on top, Draft 2 below it, Draft 1 at the bottom).

### PR DESCRIPTION
**Pull request by mcjefdreal**
## Summary

Fixes the draft collapsible order on the lab page (fixes #147). Previously, `itertools.groupby` was used, which produced an array that lost the descending order of drafts. The fix uses `Object.groupBy` with a `map`, to preserve the intended order.

## Implementation Notes

- Uses `Object.groupBy` with a `map` instead of `itertools.groupby`
- Iterates over `data.drafts` in the desired order rather than relying on object key enumeration
- Removed unused `itertools` import

## Test Cases

- [ ] Verify drafts are displayed in descending order (3, 2, 1) on the lab page
- [ ] Verify accordion functionality still works correctly

### CODE REVIEW

File: src/routes/dashboard/lab/+page.svelte [hunk 1]
```diff
@@ -9,20 +8,25 @@
...
-          givenName: givenName ?? '',
-          familyName: familyName ?? '',
-          avatarUrl: avatarUrl ?? '',
-        })),
-      }),
-    ),
-  );
+  const membersByDraft = $derived.by(() => {
+    const grouped = Object.groupBy(members, ({ draftId }) => Number(draftId));
+
```
Comment (BastiDood) [inline src/routes/dashboard/lab/+page.svelte]: Nitpick: no need for the extra space.
```suggestion
```

**Review by BastiDood — APPROVED** [review]
Nice, this was an unexpected rabbit hole earlier. 🚀
